import { useEffect, useState, type FormEvent, type ReactNode } from "react";
import {
  PiAddressBook, PiArrowLeft, PiCalendarBlank, PiCaretLeft, PiCaretRight, PiChartLineUp, PiCheck,
  PiChatCircleText, PiCircleNotch, PiClipboardText, PiClock, PiCurrencyDollar, PiFileText, PiKanban, PiLockKey, PiMagnifyingGlass, PiPlus,
  PiSignOut, PiSparkle, PiSquaresFour, PiUserCircle, PiUsersThree, PiWarning, PiX,
} from "react-icons/pi";
import type { CrmAppointment, CrmContact, CrmConversation, CrmLead, CrmStage, CrmTask, Deliverable, WorkItem } from "../shared/schemas";
import { api, type CrmData, type DeliverableGrantSummary } from "./api";
import { useDialogFocus } from "./useDialogFocus";

type View = "overview" | "pipeline" | "contacts" | "conversations" | "work" | "calendar";
const stages: Array<{ id: CrmStage; label: string }> = [
  { id: "new", label: "New inquiry" }, { id: "qualified", label: "Qualified" }, { id: "consultation", label: "Consultation" },
  { id: "proposal", label: "Proposal" }, { id: "booked", label: "Booked" }, { id: "won", label: "Won" },
];
const money = (value: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value);
const shortDate = (value: string) => new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" }).format(new Date(value));
const dateKey = (date: Date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`;

export function CrmApp({ onBack }: { onBack: () => void }) {
  const [auth, setAuth] = useState<{ configured: boolean; authenticated: boolean } | null>(null);
  const [data, setData] = useState<CrmData | null>(null);
  const [error, setError] = useState<string | null>(null);
  const load = async () => {
    const status = await api.crmAuth(); setAuth(status);
    if (status.authenticated) setData(await api.crmBootstrap());
  };
  useEffect(() => { load().catch((reason) => setError(reason.message)); }, []);
  if (!auth) return <CrmLoading error={error} />;
  if (!auth.authenticated) return <PrivateAccessGate configured={auth.configured} onBack={onBack} onSuccess={() => void load()} />;
  if (!data) return <CrmLoading error={error} />;
  return <CrmWorkspace data={data} onReload={async () => setData(await api.crmBootstrap())} onBack={onBack} onLogout={async () => { await api.crmLogout(); setData(null); setAuth({ configured: true, authenticated: false }); }} />;
}

function CrmLoading({ error }: { error: string | null }) {
  return <main className="crm-loading"><span className="brand-orbit"><PiSparkle /></span>{error ? <><PiWarning /><p>{error}</p></> : <><PiCircleNotch className="spin" /><p>Opening private CRM…</p></>}</main>;
}

export function PrivateAccessGate({ configured, onBack, onSuccess }: { configured: boolean; onBack: () => void; onSuccess: () => void }) {
  const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  const submit = async (event: FormEvent) => {
    event.preventDefault(); setError(null);
    if (!configured && password !== confirm) return setError("The passwords do not match.");
    setBusy(true); try { configured ? await api.crmLogin(password) : await api.crmSetup(password); onSuccess(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to unlock CRM."); } finally { setBusy(false); }
  };
  return <main className="crm-gate">
    <button className="crm-back-link" onClick={onBack}><PiArrowLeft /> Public concierge</button>
    <section><span className="crm-lock"><PiLockKey /></span><small>Samuel Studio · Owner access</small><h1>{configured ? "Welcome back" : "Secure your operating system"}</h1><p>{configured ? "Enter your local admin password to open the AI employees, CRM, records, and approvals." : "Create a private admin password. It protects every internal employee and client record from customer access."}</p>
      <form onSubmit={submit}><label>Admin password<input autoFocus type="password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder={configured ? "Enter password" : "At least 10 characters"} /></label>{!configured && <label>Confirm password<input type="password" value={confirm} onChange={(event) => setConfirm(event.target.value)} placeholder="Repeat password" /></label>}{error && <div className="crm-form-error"><PiWarning />{error}</div>}<button disabled={busy || !password}>{busy ? <PiCircleNotch className="spin" /> : <PiLockKey />}{configured ? "Open AI Operating System" : "Secure AI Operating System"}</button></form>
      <footer><PiCheck /> Local Markdown records <span>·</span> <PiCheck /> 12-hour private session</footer>
    </section>
  </main>;
}

function CrmWorkspace({ data, onReload, onBack, onLogout }: { data: CrmData; onReload: () => Promise<void>; onBack: () => void; onLogout: () => Promise<void> }) {
  const [view, setView] = useState<View>("overview"); const [query, setQuery] = useState(""); const [modal, setModal] = useState<"lead" | "appointment" | "contact" | null>(null);
  const openTasks = data.tasks.filter((item) => item.status === "open");
  const pipeline = data.leads.filter((item) => !["won", "lost"].includes(item.stage)).reduce((sum, item) => sum + item.value, 0);
  const nextAppointments = data.appointments.filter((item) => new Date(item.startAt) >= new Date() && item.status !== "cancelled").sort((a, b) => a.startAt.localeCompare(b.startAt));
  const searchContacts = data.contacts.filter((item) => `${item.name} ${item.email} ${item.company} ${item.tags.join(" ")}`.toLowerCase().includes(query.toLowerCase()));
  const nav: Array<[View, ReactNode, string]> = [["overview", <PiSquaresFour />, "Overview"], ["pipeline", <PiKanban />, "Pipeline"], ["contacts", <PiAddressBook />, "Contacts"], ["conversations", <PiChatCircleText />, "Conversations"], ["work", <PiClipboardText />, "Work queue"], ["calendar", <PiCalendarBlank />, "Calendar"]];
  return <main className="crm-shell">
    <aside className="crm-sidebar"><header><span className="brand-orbit tiny"><PiSparkle /></span><div><strong>Samuel Studio</strong><small>Client operations</small></div></header><nav>{nav.map(([id, icon, label]) => <button key={id} className={view === id ? "active" : ""} onClick={() => setView(id)}>{icon}<span>{label}</span>{id === "contacts" && <b>{data.contacts.length}</b>}{id === "conversations" && data.conversations.length > 0 && <b>{data.conversations.length}</b>}</button>)}</nav><div className="crm-sidebar-foot"><button onClick={onBack}><PiArrowLeft /><span>AI employees</span></button><button onClick={() => void onLogout()}><PiSignOut /><span>Lock CRM</span></button><small><PiLockKey /> Owner-only workspace</small></div></aside>
    <section className="crm-main"><header className="crm-topbar"><div><p>Private CRM</p><h1>{nav.find(([id]) => id === view)?.[2]}</h1></div><div className="crm-top-actions"><label><PiMagnifyingGlass /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search clients…" /></label><button className="crm-icon-button" title="Appointments" onClick={() => setView("calendar")}><PiCalendarBlank /></button><button className="crm-primary" onClick={() => setModal("lead")}><PiPlus /> New lead</button></div></header>
      <div className="crm-content">{view === "overview" && <Overview data={data} pipeline={pipeline} openTasks={openTasks} appointments={nextAppointments} onView={setView} onReload={onReload} />}{view === "pipeline" && <Pipeline data={data} onReload={onReload} />}{view === "contacts" && <Contacts contacts={searchContacts} leads={data.leads} onAdd={() => setModal("contact")} />}{view === "conversations" && <Conversations conversations={data.conversations} contacts={data.contacts} leads={data.leads} query={query} />}{view === "work" && <WorkQueue items={data.workItems} deliverables={data.deliverables} contacts={data.contacts} onReload={onReload} />}{view === "calendar" && <Calendar data={data} onBook={() => setModal("appointment")} onReload={onReload} />}</div>
    </section>
    {modal === "lead" && <LeadModal data={data} onClose={() => setModal(null)} onDone={async () => { setModal(null); await onReload(); }} />}
    {modal === "contact" && <ContactModal onClose={() => setModal(null)} onDone={async () => { setModal(null); await onReload(); }} />}
    {modal === "appointment" && <AppointmentModal data={data} onClose={() => setModal(null)} onDone={async () => { setModal(null); await onReload(); }} />}
  </main>;
}

function Overview({ data, pipeline, openTasks, appointments, onView, onReload }: { data: CrmData; pipeline: number; openTasks: CrmTask[]; appointments: CrmAppointment[]; onView: (view: View) => void; onReload: () => Promise<void> }) {
  const proposals = data.leads.filter((item) => item.stage === "proposal"); const won = data.leads.filter((item) => item.stage === "won").reduce((sum, item) => sum + item.value, 0);
  return <div className="crm-overview"><section className="crm-welcome"><div><small>Tuesday’s command center</small><h2>Keep every opportunity moving.</h2><p>Your Samuel Studio inquiries, projects, and appointments in one private place.</p></div><span><PiChartLineUp /><b>{data.leads.length}</b><small>active opportunities</small></span></section>
    <div className="crm-metrics"><Metric icon={<PiCurrencyDollar />} label="Open pipeline" value={money(pipeline)} note="Across three studio brands" /><Metric icon={<PiUsersThree />} label="Client records" value={String(data.contacts.length)} note={`${data.leads.length} opportunities`} /><Metric icon={<PiCalendarBlank />} label="Upcoming" value={String(appointments.length)} note={appointments[0] ? `Next ${shortDate(appointments[0].startAt)}` : "No appointments"} /><Metric icon={<PiClock />} label="Needs attention" value={String(openTasks.length + data.workItems.filter((item) => !["delivered", "closed"].includes(item.status)).length)} note={`${openTasks.length} tasks · ${data.workItems.filter((item) => !["delivered", "closed"].includes(item.status)).length} tracked requests`} /></div>
    <div className="crm-overview-grid"><section className="crm-panel crm-pipeline-preview"><PanelHeader title="Pipeline at a glance" action="Open pipeline" onClick={() => onView("pipeline")} /><div>{stages.slice(0, 5).map((stage) => { const leads = data.leads.filter((item) => item.stage === stage.id); return <article key={stage.id}><header><span><i className={`stage-${stage.id}`} />{stage.label}</span><b>{leads.length}</b></header><strong>{money(leads.reduce((sum, item) => sum + item.value, 0))}</strong><div><i style={{ width: `${Math.max(8, Math.min(100, leads.length * 28))}%` }} /></div></article>; })}</div></section>
      <section className="crm-panel"><PanelHeader title="Next appointments" action="Calendar" onClick={() => onView("calendar")} /><div className="crm-agenda">{appointments.slice(0, 3).map((item) => { const contact = data.contacts.find((candidate) => candidate.id === item.contactId); return <article key={item.id}><time><b>{new Date(item.startAt).getDate()}</b><span>{new Intl.DateTimeFormat("en-US", { month: "short" }).format(new Date(item.startAt))}</span></time><div><strong>{item.title}</strong><small>{shortDate(item.startAt)} · {contact?.name}</small></div><i /></article>; })}{!appointments.length && <p>No upcoming appointments.</p>}</div></section>
      <section className="crm-panel crm-tasks"><PanelHeader title="Today’s focus" /><div>{openTasks.slice(0, 4).map((task) => <label key={task.id}><button aria-label={`Complete ${task.title}`} onClick={async () => { await api.crmUpdateTask(task.id, { status: "done" }); await onReload(); }}><PiCheck /></button><span><strong>{task.title}</strong><small>{task.priority} priority {task.dueAt ? `· ${shortDate(task.dueAt)}` : ""}</small></span></label>)}{!openTasks.length && <p>Everything is caught up.</p>}</div></section>
      <section className="crm-panel crm-activity"><PanelHeader title="Recent activity" /><div>{data.activities.slice(0, 5).map((item) => <article key={item.id}><span className={`activity-${item.type}`}>{item.type === "appointment" ? <PiCalendarBlank /> : item.type === "task" ? <PiCheck /> : <PiUserCircle />}</span><div><strong>{item.summary}</strong><small>{shortDate(item.createdAt)} · {item.actor}</small></div></article>)}</div></section>
    </div><small className="crm-won-note">Closed revenue: {money(won)}</small></div>;
}

function Metric({ icon, label, value, note }: { icon: ReactNode; label: string; value: string; note: string }) { return <article className="crm-metric"><span>{icon}</span><div><small>{label}</small><strong>{value}</strong><p>{note}</p></div></article>; }
function PanelHeader({ title, action, onClick }: { title: string; action?: string; onClick?: () => void }) { return <header className="crm-panel-header"><h3>{title}</h3>{action && <button onClick={onClick}>{action}<PiCaretRight /></button>}</header>; }

function Pipeline({ data, onReload }: { data: CrmData; onReload: () => Promise<void> }) {
  const contact = (id: string) => data.contacts.find((item) => item.id === id);
  return <div className="crm-pipeline"><div className="crm-section-intro"><div><h2>Opportunity pipeline</h2><p>Move projects forward as conversations become booked work.</p></div><span>{money(data.leads.filter((item) => !["lost", "won"].includes(item.stage)).reduce((sum, item) => sum + item.value, 0))}<small> open value</small></span></div><div className="crm-kanban">{stages.map((stage) => { const leads = data.leads.filter((item) => item.stage === stage.id); return <section key={stage.id}><header><span><i className={`stage-${stage.id}`} />{stage.label}</span><b>{leads.length}</b></header><small>{money(leads.reduce((sum, item) => sum + item.value, 0))}</small><div>{leads.map((lead) => <article key={lead.id}><div className="crm-card-brand">{lead.project}</div><h3>{lead.title}</h3><p>{contact(lead.contactId)?.name}</p><strong>{money(lead.value)}</strong><footer><span className={`priority-${lead.priority}`}>{lead.priority}</span><select aria-label={`Stage for ${lead.title}`} value={lead.stage} onChange={async (event) => { await api.crmUpdateLead(lead.id, { stage: event.target.value as CrmStage }); await onReload(); }}>{stages.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></footer></article>)}</div></section>; })}</div></div>;
}

function Contacts({ contacts, leads, onAdd }: { contacts: CrmContact[]; leads: CrmLead[]; onAdd: () => void }) {
  return <div className="crm-contacts"><div className="crm-section-intro"><div><h2>Client directory</h2><p>People, brands, context, and every active opportunity.</p></div><button className="crm-secondary" onClick={onAdd}><PiPlus /> Add contact</button></div><section className="crm-contact-table"><header><span>Client</span><span>Company</span><span>Source</span><span>Open value</span><span>Last updated</span></header>{contacts.map((contact) => { const related = leads.filter((lead) => lead.contactId === contact.id); return <article key={contact.id}><span className="crm-contact-name"><i>{contact.name.split(" ").map((part) => part[0]).join("").slice(0, 2)}</i><span><strong>{contact.name}</strong><small>{contact.email}</small></span></span><span>{contact.company || "Independent"}</span><span><b className="crm-source">{contact.source}</b></span><span>{money(related.filter((lead) => !["lost", "won"].includes(lead.stage)).reduce((sum, lead) => sum + lead.value, 0))}</span><time>{new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric" }).format(new Date(contact.updatedAt))}</time></article>; })}</section></div>;
}

type TranscriptEvent = { heading: string; at: string; body: string; kind: "customer" | "receptionist" | "specialist" | "handoff" | "system" };
const conversationStatusLabel: Record<CrmConversation["status"], string> = { new: "New inquiry", awaiting_customer: "Waiting on customer", awaiting_owner: "Owner action", follow_up_due: "Follow-up due", resolved: "Resolved" };
function transcriptEvents(markdown: string): TranscriptEvent[] {
  const events: TranscriptEvent[] = [];
  for (const match of markdown.matchAll(/^## (.+?) — ([^\n]+)\n\n([\s\S]*?)(?=^## |$(?![\s\S]))/gm)) {
    const heading = match[1]; if (heading === "CRM linkage") continue;
    const body = match[3].replace(/<!-- EVENT [\s\S]*? -->/g, "").trim();
    const kind = heading === "Customer" ? "customer" : heading === "Receptionist" ? "receptionist" : heading.endsWith(" Specialist") ? "specialist" : heading.startsWith("Internal handoff") ? "handoff" : "system";
    events.push({ heading, at: match[2], body, kind });
  }
  return events;
}

function Conversations({ conversations, contacts, leads, query }: { conversations: CrmConversation[]; contacts: CrmContact[]; leads: CrmLead[]; query: string }) {
  const visible = conversations.filter((item) => `${item.customerName} ${item.customerEmail} ${item.initialNeed} ${item.departments.join(" ")}`.toLowerCase().includes(query.toLowerCase()));
  const [selectedId, setSelectedId] = useState<string | null>(visible[0]?.id ?? null); const [content, setContent] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  useEffect(() => { if (!selectedId && visible[0]) setSelectedId(visible[0].id); }, [selectedId, visible]);
  useEffect(() => { if (!selectedId) { setContent(""); return; } setBusy(true); setError(null); api.crmConversation(selectedId).then((result) => setContent(result.content)).catch((reason) => setError(reason.message)).finally(() => setBusy(false)); }, [selectedId]);
  const selected = conversations.find((item) => item.id === selectedId); const contact = contacts.find((item) => item.id === selected?.contactId); const lead = leads.find((item) => item.id === selected?.leadId); const events = transcriptEvents(content);
  const attention = conversations.filter((item) => ["new", "awaiting_owner", "follow_up_due"].includes(item.status)).length;
  return <div className="crm-conversations"><div className="crm-section-intro"><div><h2>Conversation inbox</h2><p>Every public inquiry, Receptionist reply, and private specialist handoff.</p></div><span>{attention}<small> need attention</small></span></div>{!conversations.length ? <section className="crm-conversation-empty"><PiChatCircleText /><h3>No customer conversations yet</h3><p>New public Receptionist inquiries will appear here automatically and remain backed by their Markdown transcript.</p></section> : <div className="crm-conversation-layout"><aside className="crm-inbox-list"><header><span>All conversations</span><b>{visible.length}</b></header>{visible.map((item) => <button key={item.id} className={selectedId === item.id ? "active" : ""} onClick={() => setSelectedId(item.id)}><span className="crm-inbox-avatar">{item.customerName.split(" ").map((part) => part[0]).join("").slice(0, 2)}</span><span><strong>{item.customerName}</strong><small>{item.initialNeed}</small><i>{item.departments.length ? item.departments.join(" · ") : "Receptionist"}</i></span><time>{shortDate(item.lastActivity)}</time>{["new", "awaiting_owner", "follow_up_due"].includes(item.status) && <em>{conversationStatusLabel[item.status]}</em>}</button>)}{!visible.length && <p>No conversations match your search.</p>}</aside><section className="crm-transcript">{selected && <><header><div><span className="crm-transcript-avatar">{selected.customerName.split(" ").map((part) => part[0]).join("").slice(0, 2)}</span><span><h3>{selected.customerName}</h3><p>{selected.customerEmail}{contact?.phone ? ` · ${contact.phone}` : ""}</p></span></div><span className={`crm-conversation-status ${selected.status}`}>{conversationStatusLabel[selected.status]}</span></header><div className="crm-conversation-context"><span><small>Inquiry</small><strong>{lead?.title ?? "Public inquiry"}</strong></span><span><small>Messages</small><strong>{selected.messageCount}</strong></span><span><small>Consulted</small><strong>{selected.departments.join(", ") || "Receptionist only"}</strong></span></div><div className="crm-transcript-scroll">{busy ? <PiCircleNotch className="spin" /> : error ? <div className="crm-form-error"><PiWarning />{error}</div> : events.map((event, index) => event.kind === "handoff" ? <div className="crm-handoff-event" key={`${event.at}-${index}`}><PiUsersThree /><span><strong>{event.heading.replace("Internal handoff: ", "Consulted ")}</strong><small>Private internal event · {shortDate(event.at)}</small></span></div> : <article className={`crm-transcript-message ${event.kind}`} key={`${event.at}-${index}`}><header><strong>{event.heading}</strong><time>{shortDate(event.at)}</time></header><p>{event.body}</p></article>)}</div><footer><PiFileText /><span><strong>Canonical Markdown transcript</strong><small>{selected.file}</small></span></footer></>}</section></div>}</div>;
}

function WorkQueue({ items, deliverables, contacts, onReload }: { items: WorkItem[]; deliverables: Deliverable[]; contacts: CrmContact[]; onReload: () => Promise<void> }) {
  const groups: WorkItem["status"][] = ["awaiting_owner", "collecting", "in_progress", "ready", "delivered", "closed"];
  const contactName = (id: string | null) => contacts.find((item) => item.id === id)?.name ?? "Internal work";
  return <div className="crm-work-queue"><div className="crm-section-intro"><div><h2>Tracked work and deliverables</h2><p>Every promise has an owner, status, next step, and canonical Markdown record.</p></div><span>{items.filter((item) => !["delivered", "closed"].includes(item.status)).length}<small> active requests</small></span></div>
    {!items.length ? <section className="crm-conversation-empty"><PiClipboardText /><h3>No tracked work yet</h3><p>Customer quote, report, proposal, research, and appointment requests will appear here automatically.</p></section> : <div className="crm-work-columns">{groups.map((status) => {
      const matching = items.filter((item) => item.status === status); if (!matching.length) return null;
      return <section key={status}><header><span>{status.replaceAll("_", " ")}</span><b>{matching.length}</b></header><div>{matching.map((item) => <article key={item.id}><small>{item.kind} · {item.employeeId}</small><h3>{item.title}</h3><p>{item.summary}</p><div><span>{contactName(item.contactId)}</span><time>{shortDate(item.updatedAt)}</time></div><footer><strong>{item.nextStep || "No next step recorded"}</strong>{!["delivered", "closed"].includes(item.status) && <select aria-label={`Status for ${item.title}`} value={item.status} onChange={async (event) => { await api.updateWorkItem(item.id, { status: event.target.value as WorkItem["status"] }); await onReload(); }}>{groups.filter((candidate) => candidate !== "collecting" || item.status === "collecting").map((candidate) => <option key={candidate} value={candidate}>{candidate.replaceAll("_", " ")}</option>)}</select>}</footer></article>)}</div></section>;
    })}</div>}
    {deliverables.filter((item) => item.visibility === "customer" && item.status === "delivered").length > 0 && <section className="crm-access-grants"><header><div><h3>Customer deliverable access</h3><p>Issue independent links and revoke only the grant that should stop working.</p></div></header><div>{deliverables.filter((item) => item.visibility === "customer" && item.status === "delivered").map((deliverable) => <DeliverableAccess key={deliverable.id} deliverable={deliverable} />)}</div></section>}
  </div>;
}

function DeliverableAccess({ deliverable }: { deliverable: Deliverable }) {
  const [grants, setGrants] = useState<DeliverableGrantSummary[]>([]); const [issuedUrl, setIssuedUrl] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const load = async () => setGrants(await api.deliverableGrants(deliverable.id));
  useEffect(() => { load().catch((reason) => setError(reason.message)); }, [deliverable.id]);
  return <article><div><small>{deliverable.kind}</small><strong>{deliverable.title}</strong><span>{grants.filter((grant) => !grant.revokedAt).length} active grant{grants.filter((grant) => !grant.revokedAt).length === 1 ? "" : "s"}</span></div><button className="crm-secondary" disabled={busy} onClick={async () => { setBusy(true); setError(""); try { const result = await api.issueDeliverableGrant(deliverable.id); setIssuedUrl(result.accessUrl); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to issue access."); } finally { setBusy(false); } }}>{busy ? <PiCircleNotch className="spin" /> : <PiPlus />} Issue link</button>{issuedUrl && <div className="crm-issued-link" role="status"><code>{issuedUrl}</code><button onClick={() => void navigator.clipboard.writeText(`${window.location.origin}${issuedUrl}`)}>Copy</button></div>}{grants.length > 0 && <div className="crm-grant-list">{grants.map((grant) => <span key={grant.id}><code>{grant.id}</code><time>{shortDate(grant.issuedAt)}</time>{grant.revokedAt ? <em>Revoked</em> : <button onClick={async () => { await api.revokeDeliverableGrant(deliverable.id, grant.id); if (issuedUrl) setIssuedUrl(""); await load(); }}>Revoke</button>}</span>)}</div>}{error && <p className="crm-form-error" role="alert"><PiWarning />{error}</p>}</article>;
}

function Calendar({ data, onBook, onReload }: { data: CrmData; onBook: () => void; onReload: () => Promise<void> }) {
  const [month, setMonth] = useState(() => { const value = new Date(); value.setDate(1); value.setHours(12, 0, 0, 0); return value; }); const [selected, setSelected] = useState(dateKey(new Date())); const [slots, setSlots] = useState<string[]>([]);
  useEffect(() => { api.crmAvailability(selected).then(setSlots).catch(() => setSlots([])); }, [selected, data.appointments]);
  const first = new Date(month); const offset = first.getDay(); const total = new Date(month.getFullYear(), month.getMonth() + 1, 0).getDate(); const prior = new Date(month.getFullYear(), month.getMonth(), 0).getDate();
  const cells = Array.from({ length: 42 }, (_, index) => { const day = index - offset + 1; const date = day < 1 ? new Date(month.getFullYear(), month.getMonth() - 1, prior + day) : day > total ? new Date(month.getFullYear(), month.getMonth() + 1, day - total) : new Date(month.getFullYear(), month.getMonth(), day); return { date, outside: day < 1 || day > total }; });
  const selectedAppointments = data.appointments.filter((item) => dateKey(new Date(item.startAt)) === selected && item.status !== "cancelled").sort((a, b) => a.startAt.localeCompare(b.startAt));
  return <div className="crm-calendar-view"><div className="crm-section-intro"><div><h2>Studio calendar</h2><p>Appointments, tentative customer holds, and live consultation openings.</p></div><button className="crm-primary" onClick={onBook}><PiPlus /> Book appointment</button></div><div className="crm-calendar-grid"><section className="crm-month"><header><button aria-label="Previous month" onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() - 1, 1))}><PiCaretLeft /></button><h3>{new Intl.DateTimeFormat("en-US", { month: "long", year: "numeric" }).format(month)}</h3><button aria-label="Next month" onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() + 1, 1))}><PiCaretRight /></button></header><div className="crm-weekdays">{["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"].map((day) => <span key={day}>{day}</span>)}</div><div className="crm-days">{cells.map(({ date, outside }) => { const key = dateKey(date); const count = data.appointments.filter((item) => dateKey(new Date(item.startAt)) === key && item.status !== "cancelled").length; return <button key={key} className={`${outside ? "outside" : ""} ${selected === key ? "selected" : ""} ${key === dateKey(new Date()) ? "today" : ""}`} onClick={() => setSelected(key)}><b>{date.getDate()}</b>{count > 0 && <span>{count} event{count > 1 ? "s" : ""}</span>}</button>; })}</div></section><aside className="crm-day-panel"><header><small>Selected day</small><h3>{new Intl.DateTimeFormat("en-US", { weekday: "long", month: "long", day: "numeric" }).format(new Date(`${selected}T12:00:00`))}</h3></header><div className="crm-day-appointments">{selectedAppointments.map((item) => <article key={item.id}><time>{new Intl.DateTimeFormat("en-US", { hour: "numeric", minute: "2-digit" }).format(new Date(item.startAt))}</time><div><strong>{item.title}</strong><small>{item.location}</small><select aria-label={`Status for ${item.title}`} value={item.status} onChange={async (event) => { await api.crmUpdateAppointment(item.id, { status: event.target.value as CrmAppointment["status"] }); await onReload(); }}><option value="tentative">Tentative</option><option value="confirmed">Confirmed</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select></div></article>)}{!selectedAppointments.length && <p>No appointments booked.</p>}</div><div className="crm-openings"><small>Available one-hour openings</small><div>{slots.slice(0, 6).map((slot) => <span key={slot}>{new Intl.DateTimeFormat("en-US", { hour: "numeric" }).format(new Date(slot))}</span>)}</div></div></aside></div></div>;
}

function Dialog({ title, onClose, children }: { title: string; onClose: () => void; children: ReactNode }) {
  const dialogRef = useDialogFocus<HTMLElement>(onClose);
  return <div className="crm-modal-backdrop" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><section ref={dialogRef} tabIndex={-1} className="crm-modal" role="dialog" aria-modal="true" aria-label={title}><header><div><small>Samuel Studio CRM</small><h2>{title}</h2></div><button aria-label="Close" onClick={onClose}><PiX /></button></header>{children}</section></div>;
}

function LeadModal({ data, onClose, onDone }: { data: CrmData; onClose: () => void; onDone: () => void }) {
  const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false); const [form, setForm] = useState({ contactId: data.contacts[0]?.id ?? "", title: "", project: "Samuel.Studio", service: "Photography", stage: "new" as CrmStage, value: 0, currency: "USD", owner: "Samuel", priority: "normal" as const, summary: "", nextStep: "Follow up with inquiry", followUpAt: null, tags: [] as string[] });
  return <Dialog title="Create a new lead" onClose={onClose}><form className="crm-modal-form" onSubmit={async (event) => { event.preventDefault(); setBusy(true); setError(null); try { await api.crmCreateLead(form); onDone(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to save lead."); } finally { setBusy(false); } }}><label>Contact<select value={form.contactId} onChange={(e) => setForm({ ...form, contactId: e.target.value })}>{data.contacts.map((item) => <option key={item.id} value={item.id}>{item.name} · {item.company}</option>)}</select></label><label className="wide">Opportunity title<input required value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} placeholder="e.g. Editorial launch campaign" /></label><label>Studio<select value={form.project} onChange={(e) => setForm({ ...form, project: e.target.value })}><option>Samuel.Studio</option><option>Samuel.Colombia</option><option>Samuel.Studio.dev</option></select></label><label>Service<input value={form.service} onChange={(e) => setForm({ ...form, service: e.target.value })} /></label><label>Estimated value<input type="number" min="0" value={form.value} onChange={(e) => setForm({ ...form, value: Number(e.target.value) })} /></label><label>Stage<select value={form.stage} onChange={(e) => setForm({ ...form, stage: e.target.value as CrmStage })}>{stages.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></label><label className="wide">Notes<textarea value={form.summary} onChange={(e) => setForm({ ...form, summary: e.target.value })} placeholder="Project scope, goals, or important context" /></label>{error && <div className="crm-form-error wide"><PiWarning />{error}</div>}<footer className="wide"><button type="button" className="crm-secondary" onClick={onClose}>Cancel</button><button className="crm-primary" disabled={busy}>{busy ? <PiCircleNotch className="spin" /> : <PiPlus />}Create lead</button></footer></form></Dialog>;
}

function ContactModal({ onClose, onDone }: { onClose: () => void; onDone: () => void }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [form, setForm] = useState({ name: "", email: "", phone: "", company: "", location: "", source: "Direct", tags: [] as string[], notes: "" });
  return <Dialog title="Add a contact" onClose={onClose}><form className="crm-modal-form" onSubmit={async (event) => { event.preventDefault(); setBusy(true); try { await api.crmCreateContact(form); onDone(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to save contact."); } finally { setBusy(false); } }}><label>Full name<input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><label>Email<input type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></label><label>Company<input value={form.company} onChange={(e) => setForm({ ...form, company: e.target.value })} /></label><label>Phone<input value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} /></label><label>Location<input value={form.location} onChange={(e) => setForm({ ...form, location: e.target.value })} /></label><label>Source<select value={form.source} onChange={(e) => setForm({ ...form, source: e.target.value })}><option>Direct</option><option>Referral</option><option>Instagram</option><option>Samuel.Studio</option><option>Samuel.Colombia</option><option>Samuel.Studio.dev</option></select></label>{error && <div className="crm-form-error wide"><PiWarning />{error}</div>}<footer className="wide"><button type="button" className="crm-secondary" onClick={onClose}>Cancel</button><button className="crm-primary" disabled={busy}>Add contact</button></footer></form></Dialog>;
}

function AppointmentModal({ data, onClose, onDone }: { data: CrmData; onClose: () => void; onDone: () => void }) {
  const start = new Date(Date.now() + 86400000); start.setHours(10, 0, 0, 0); const local = `${dateKey(start)}T10:00`;
  const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [form, setForm] = useState({ contactId: data.contacts[0]?.id ?? "", leadId: null as string | null, title: "Creative consultation", startAt: local, type: "Consultation", location: "Video call", notes: "" });
  return <Dialog title="Book an appointment" onClose={onClose}><form className="crm-modal-form" onSubmit={async (event) => { event.preventDefault(); setBusy(true); setError(null); try { const startAt = new Date(form.startAt).toISOString(); await api.crmCreateAppointment({ ...form, startAt, endAt: new Date(new Date(startAt).getTime() + 3600000).toISOString(), status: "confirmed" }); onDone(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to book appointment."); } finally { setBusy(false); } }}><label>Client<select value={form.contactId} onChange={(e) => setForm({ ...form, contactId: e.target.value })}>{data.contacts.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Date and time<input type="datetime-local" required value={form.startAt} onChange={(e) => setForm({ ...form, startAt: e.target.value })} /></label><label className="wide">Title<input required value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /></label><label>Type<select value={form.type} onChange={(e) => setForm({ ...form, type: e.target.value })}><option>Consultation</option><option>Discovery call</option><option>Production meeting</option><option>Review</option></select></label><label>Location<input value={form.location} onChange={(e) => setForm({ ...form, location: e.target.value })} /></label>{error && <div className="crm-form-error wide"><PiWarning />{error}</div>}<footer className="wide"><button type="button" className="crm-secondary" onClick={onClose}>Cancel</button><button className="crm-primary" disabled={busy}>{busy ? <PiCircleNotch className="spin" /> : <PiCalendarBlank />}Book appointment</button></footer></form></Dialog>;
}
